version: '3.8'

services:
  database:
    image: postgres:16
    container_name: postgres-spring-api
    environment:
      - POSTGRES_USER=raindrop
      - POSTGRES_PASSWORD=doorway
      - POSTGRES_DB=mineracaodados_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pgdata: